<a href="https://colab.research.google.com/github/tomcat472/pytorch/blob/main/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# arange method ဖြင့် tensor တခုပြုလုပ်ခြင်း
X=torch.arange(1,10)
X

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(X) # 1 dim array 
print(X.shape) #variable ထဲတွင်ပါဝင်သော element အရေအတွက်အားကြည့်ခြင်း

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [4]:
X.reshape(3,3)
# reshape method ဖြင့် 3 row, 3 col ပါသော 2 dim tensor တခုပြုလုပ်ခြင်း

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
# reshaped ပြုလုပ်ထားသော tensor အား variable အသစ်ထဲသို့ assgin ပြုလုပ်ခြင်း
X_reshaped=X.reshape(3,3)
X_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# reshape method သည် numpy ကဲ့သို့ဖြစ်ပြီး ဆခွဲကိန်းခွဲကာ သတ်မှတ်လို့ရသည်။
another_reshape=X.reshape(1,3,3)
another_reshape
# ဒီမှာဆိုရင် 3rows, 3cols ပါသော 3 Dimensional tensor ရမည်ဖြစ်ပါတယ်။

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [7]:
# view method သည် tensor အား ကိုယ်မြင်လိုသည့်ပုံစံဖြင့် ကြည့်ခြင်းဖြစ်သည်။ reshape ကဲ့သို့ဖြစ်သည်။
# return a view of tensor of certain shape but keep the same memoray as the original tensor
z=X.view(1,9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
print(z.shape)

torch.Size([1, 9])


In [9]:
z.view(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
z[0,0]=500
z

tensor([[500,   2,   3,   4,   5,   6,   7,   8,   9]])

In [11]:
print(z)
print(X)

tensor([[500,   2,   3,   4,   5,   6,   7,   8,   9]])
tensor([500,   2,   3,   4,   5,   6,   7,   8,   9])


In [12]:
y=X.reshape(1,9)
print(y)

tensor([[500,   2,   3,   4,   5,   6,   7,   8,   9]])


In [13]:
y[0,2]=100
print(y)

tensor([[500,   2, 100,   4,   5,   6,   7,   8,   9]])


In [14]:
print(X)

tensor([500,   2, 100,   4,   5,   6,   7,   8,   9])


In [15]:
z==y

tensor([[True, True, True, True, True, True, True, True, True]])

In [16]:
# stack
# combine multiple tensors on top of each other (vstack) or side by side (hstack)
x_stacked=torch.stack([X,X,X,X],dim=0)
x_stacked

tensor([[500,   2, 100,   4,   5,   6,   7,   8,   9],
        [500,   2, 100,   4,   5,   6,   7,   8,   9],
        [500,   2, 100,   4,   5,   6,   7,   8,   9],
        [500,   2, 100,   4,   5,   6,   7,   8,   9]])

In [17]:
x_stacked=torch.stack([X,X,X,X],dim=1)
x_stacked

tensor([[500, 500, 500, 500],
        [  2,   2,   2,   2],
        [100, 100, 100, 100],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5],
        [  6,   6,   6,   6],
        [  7,   7,   7,   7],
        [  8,   8,   8,   8],
        [  9,   9,   9,   9]])

In [18]:
# slecting data from tensors
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
print(x[0]) #print 1st dim
print(x[0][0],x[0,0]) #dim=1
print(x[0][0][0])#last dim

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3]) tensor([1, 2, 3])
tensor(1)


In [20]:
x[:,0]

tensor([[1, 2, 3]])

In [21]:
x[:,:,1]

tensor([[2, 5, 8]])

In [22]:
print(x[0,0,:])
print(x[0][2][2])
print(x[:,:,2])

tensor([1, 2, 3])
tensor(9)
tensor([[3, 6, 9]])


In [23]:
# numpy to tensor
import numpy as np
arr=np.arange(1.0,8.0)
tensor=torch.from_numpy(arr)
print(arr,tensor)
print(arr.shape,tensor.shape)
print(arr.dtype,torch.dtype)
# numpy ရဲ့ default dtype က float64
# pytorch ရဲ့ dafault dtype က float32

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
(7,) torch.Size([7])
float64 <class 'torch.dtype'>


In [24]:
arr=arr+1
print(arr)
print(tensor)

[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [25]:
# Tensor to numpy
tensor_new=torch.ones(7)
tensor_new

tensor([1., 1., 1., 1., 1., 1., 1.])

In [26]:
numpy_tensor=tensor_new.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [27]:
tensor_new=tensor_new+1
print(tensor_new)
print(numpy_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1. 1. 1.]


In [28]:
# reprodubility
# random seed ==> to reduce the randomness in neural networls and pytorch

In [29]:
A=torch.rand(3,4)
B=torch.rand(3,4)
print(A)
print(B)
print(A==B)

tensor([[0.2599, 0.9345, 0.8779, 0.8414],
        [0.0188, 0.8550, 0.8771, 0.2146],
        [0.2782, 0.8211, 0.7027, 0.1842]])
tensor([[0.9583, 0.2598, 0.4294, 0.0411],
        [0.0302, 0.6134, 0.5465, 0.0166],
        [0.9364, 0.3329, 0.8071, 0.4587]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [30]:
# set random seed
seed=42
torch.manual_seed(seed)
C=torch.rand(3,4)
D=torch.rand(3,4)
print(C)
print(D)
print(C==D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [31]:
seed=42
torch.manual_seed(seed)
E=torch.rand(3,4)

torch.manual_seed(seed)
F=torch.rand(3,4)

print(E)
print(F)
print(E==F)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
