<a href="https://colab.research.google.com/github/tomcat472/pytorch/blob/main/pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing pytorch
import torch
# pytorch က numpy နဲ့သဘောသဘာဝချင်းဆင်တူပါတယ်။

In [2]:
# checking pytorch version
torch.__version__

'1.12.1+cu113'

In [3]:
# scalar
# single number ဖြင့်ဖော်ပြတယ်။
# zero dimension ဖြစ်တယ်။
scalar=torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
# dimension စစ်ခြင်း
scalar.ndim

0

In [5]:
# pytorch site ထဲက tensor ကိုဖတ်ခြင်း
scalar.item()

7

In [6]:
# vector တခုတည်ဆောက်ခြင်း
# vector ဆိုတာ maganitude နဲ့ direction ပါတယ်။
# ဘယ်လို direction လဲဆိုတော့ အပူချိန်/လေတိုက်နှုန်းလို သတ်မှတ်ထားတဲ့ direction အတိုင်းသွားရင် positive
# ဆန့်ကျင်ဘက် direction အတိုင်းသွားရင် negative ရတဲ့သဘောမျိုးကို ဆိုလိုတာဖြစ်တယ်။
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [7]:
vector.ndim

1

In [8]:
# matrix တည်ဆောက်ခြင်း
# matrix ဆိုတာ ၁၀ တန်းသင်္ချာထဲကအတိုင်းပဲ row,col အတွဲဖြစ်တယ်။ tabular ပုံစံကို ပြေးမြင်ရင်ရတယ်။
matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# tensor တခုတည်ဆောက်ခြင်း
# tensor ဆိုတာ nth dimensional matrix ဖြစ်ပါတယ်။
# 3 dimension ကနေစပြီး tensor လို့ခေါ်ပါတယ်။
tensor=torch.tensor([[[1,2,3],[4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [12]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 2, 3])


In [13]:
# Slicing and indexing

In [14]:
matrix

tensor([[1, 2],
        [3, 4]])

In [15]:
matrix[0]

tensor([1, 2])

In [16]:
matrix[0,1]

tensor(2)