<a href="https://colab.research.google.com/github/tomcat472/pytorch/blob/main/pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing pytorch
import torch
# pytorch က numpy နဲ့သဘောသဘာဝချင်းဆင်တူပါတယ်။

In [2]:
# checking pytorch version
torch.__version__

'1.12.1+cu113'

In [3]:
# scalar
# single number ဖြင့်ဖော်ပြတယ်။
# zero dimension ဖြစ်တယ်။
scalar=torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
# dimension စစ်ခြင်း
scalar.ndim

0

In [5]:
# pytorch site ထဲက tensor ကိုဖတ်ခြင်း
scalar.item()

7

In [6]:
# vector တခုတည်ဆောက်ခြင်း
# vector ဆိုတာ maganitude နဲ့ direction ပါတယ်။
# ဘယ်လို direction လဲဆိုတော့ အပူချိန်/လေတိုက်နှုန်းလို သတ်မှတ်ထားတဲ့ direction အတိုင်းသွားရင် positive
# ဆန့်ကျင်ဘက် direction အတိုင်းသွားရင် negative ရတဲ့သဘောမျိုးကို ဆိုလိုတာဖြစ်တယ်။
vector=torch.tensor([2,3])
vector

tensor([2, 3])

In [7]:
vector.ndim

1

In [8]:
# matrix တည်ဆောက်ခြင်း
# matrix ဆိုတာ ၁၀ တန်းသင်္ချာထဲကအတိုင်းပဲ row,col အတွဲဖြစ်တယ်။ tabular ပုံစံကို ပြေးမြင်ရင်ရတယ်။
matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# tensor တခုတည်ဆောက်ခြင်း
# tensor ဆိုတာ nth dimensional matrix ဖြစ်ပါတယ်။
# 3 dimension ကနေစပြီး tensor လို့ခေါ်ပါတယ်။
tensor=torch.tensor([[[1,2,3],[4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [12]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 2, 3])


In [13]:
# Slicing and indexing

In [14]:
matrix

tensor([[1, 2],
        [3, 4]])

In [15]:
matrix[0]

tensor([1, 2])

In [16]:
matrix[0,1]

tensor(2)

In [17]:
# random tensor
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.7112, 0.7934, 0.9579, 0.1765],
        [0.4005, 0.1657, 0.2454, 0.1486],
        [0.4817, 0.0215, 0.5104, 0.5847]])

In [18]:
print(rand_tensor.ndim,rand_tensor.shape)

2 torch.Size([3, 4])


In [19]:
# zeros tensor and ones tensor
zeros=torch.zeros(3,4)
ones=torch.ones(3,4)
print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
print(zeros.dtype,'/',ones.dtype)

torch.float32 / torch.float32


In [21]:
# tensor range
range=torch.arange(0,100,10)
range
# python range နဲ့တူ၊ numpy arange fungtion နဲ့တူ

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
# ကိုယ်ဖန်တီးထားတဲ့ဟာတွေထဲကို zeros နဲ့ ones များထည့်ခြင်း
tensor_zeros=torch.zeros_like(range)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
tensor_ones=torch.ones_like(range)
tensor_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
# Tensor မှာဖြစ်လေ့ဖြစ်ထရှိတဲ့ error က data type error, shape error နဲ့ device error ဖြစ်ပါတယ်။

In [25]:
# datatype စစ်ခြင်း
tensor_ones.dtype

torch.int64

In [26]:
# datatype ပြောင်းခြင်း
tensor_ones.type(torch.float32)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
# manipulating tensors
A=torch.tensor([32,2])
A

tensor([32,  2])

In [28]:
# addition
print(A+100)
print(torch.add(A,100))

# subtraction
print(A-100)
print(torch.subtract(A,100))

# multiplication
print(A*10)
print(torch.mul(A,10))

tensor([132, 102])
tensor([132, 102])
tensor([-68, -98])
tensor([-68, -98])
tensor([320,  20])
tensor([320,  20])


In [29]:
# matrix multiplication (dot product)
B=torch.tensor([[1,2],[3,4]])
B

tensor([[1, 2],
        [3, 4]])

In [30]:
# element wise multiplication
B * B

tensor([[ 1,  4],
        [ 9, 16]])

In [31]:
# matric multopliaction
torch.matmul(B,B)

tensor([[ 7, 10],
        [15, 22]])

In [32]:
B@B

tensor([[ 7, 10],
        [15, 22]])

In [33]:
# matrix မြှောက်ရင် (n*m)x(m*n) ပုံစံဖြစ်မှ matrix dot product ကို သုံးလို့ရပါတယ်။
# (2x3).(3x2) matrix ကိုမြှောက်ရင် (2x2)matrix ရတယ်။

In [34]:
C=torch.rand(3,4)
D=torch.rand(4,3)
torch.matmul(C,D)

tensor([[0.8847, 0.4920, 1.1997],
        [0.8683, 0.5647, 0.8985],
        [0.9784, 0.4523, 1.3825]])

In [35]:
# Transpose
print(C)
print(C.T)
# row ကို column ပြောင်းခြင်း၊ column ကို row ပြောင်းခြင်း

tensor([[0.5647, 0.3526, 0.1398, 0.8024],
        [0.7391, 0.0786, 0.8839, 0.3574],
        [0.3736, 0.1056, 0.7245, 0.9747]])
tensor([[0.5647, 0.7391, 0.3736],
        [0.3526, 0.0786, 0.1056],
        [0.1398, 0.8839, 0.7245],
        [0.8024, 0.3574, 0.9747]])


In [36]:
# min,max,mean,sum စသည်တို့ကိုရှာခြင်း
E=torch.arange(0,1000,20,dtype=torch.float64)
E

tensor([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200., 220.,
        240., 260., 280., 300., 320., 340., 360., 380., 400., 420., 440., 460.,
        480., 500., 520., 540., 560., 580., 600., 620., 640., 660., 680., 700.,
        720., 740., 760., 780., 800., 820., 840., 860., 880., 900., 920., 940.,
        960., 980.], dtype=torch.float64)

In [37]:
# minimum တန်ဘိုးရှာခြင်း
print(torch.min(E))
print(E.min())

tensor(0., dtype=torch.float64)
tensor(0., dtype=torch.float64)


In [38]:
# maximum တန်ဘိုးကိုရှာခြင်း
print(torch.max(E))
print(E.max())

tensor(980., dtype=torch.float64)
tensor(980., dtype=torch.float64)


In [39]:
# average ရှာခြင်း
print(torch.mean(E))
print(E.mean())

tensor(490., dtype=torch.float64)
tensor(490., dtype=torch.float64)


In [40]:
# total အားရှာခြင်း
print(torch.sum(E))
print(E.sum())

tensor(24500., dtype=torch.float64)
tensor(24500., dtype=torch.float64)


In [41]:
# finding index position of minimum and maximum
print(E.argmin())
print(E.argmax())

tensor(0)
tensor(49)


In [42]:
# index ဖြင့် တန်ဘိုးအား မှန်/မမှန်စစ်ခြင်း
E[49]

tensor(980., dtype=torch.float64)

In [43]:
# (၁၆-၈-၂၀၂၂)